PROJECT = simple_router
ERLC_OPTS = +debug_info

DEPS = cowboy ranch erwa
dep_cowboy = pkg://cowboy 0.10.0
dep_ranch = pkg://ranch 0.10.0
dep_erwa = https://github.com/bwegh/erwa.git



include ../../erlang.mk
