PROJECT = simple_router
ERLC_OPTS = +debug_info

DEPS = erwa elogger
dep_erwa = git https://github.com/ethrbh/erwa master
dep_elogger = git https://github.com/bwegh/elogger master


include ../../erlang.mk
