PROJECT = simple_router
ERLC_OPTS = +debug_info

DEPS = cowboy ranch erwa
dep_cowboy = pkg://cowboy 0.10.0
dep_ranch = pkg://ranch 0.10.0
dep_erwa = ssh://git@h1880328.stratoserver.net:6969/erwa



include ../../erlang.mk
